services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entryPoints.web.address=:80
    ports:
      - "3001:80"
      - "8080:8080"
    volumes:
      - ./app/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./app/traefik/dynamic:/etc/traefik/dynamic:ro
    networks:
      - backend

  api-gateway:
    image: node:20
    container_name: api-gateway
    working_dir: /usr/src/app
    volumes:
      - ./app/nestjs:/usr/src/app
    command: npm run start:gateway
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=Host(`api.localhost`)"
      - "traefik.http.services.api-gateway.loadbalancer.server.port=3000"
    networks:
      - backend
    depends_on:
      - user-service
      - trip-service
      - driver-service

  user-service:
    image: node:20
    container_name: user-service
    working_dir: /usr/src/app
    volumes:
      - ./app/nestjs:/usr/src/app
    command: npm run start:user
    depends_on:
      - user-db
    networks:
      - backend

  driver-service:
    image: node:20
    container_name: driver-service
    working_dir: /usr/src/app
    volumes:
      - ./app/nestjs:/usr/src/app
    command: npm run start:driver
    depends_on:
      - driver-db
    networks:
      - backend

  trip-service:
    image: node:20
    container_name: trip-service
    working_dir: /usr/src/app
    volumes:
      - ./app/nestjs:/usr/src/app
    command: npm run start:trip
    depends_on:
      - trip-db
    networks:
      - backend

  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    networks:
      - backend

  driver-db:
    image: postgres:15
    container_name: driver-db
    environment:
      POSTGRES_USER: driver
      POSTGRES_PASSWORD: password
      POSTGRES_DB: driver_db
    ports:
      - "5434:5432"
    networks:
      - backend

  trip-db:
    image: mysql:8
    container_name: trip-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: trip
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: trip_db
    ports:
      - "3307:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
