services:
  kong-database:
    image: postgres:15
    container_name: kong-database
    environment:
      POSTGRES_USER: ${KONG_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KONG_POSTGRES_PASSWORD}
      POSTGRES_DB: ${KONG_POSTGRES_DB}
    networks:
      - backend
    volumes:
      - kong_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 5s
      retries: 5
      start_period: 5s

  kong:
    build:
      context: ../kong
    container_name: kong
    networks:
      - backend
    depends_on:
      kong-database:
        condition: service_healthy
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST:  ${KONG_DATABASE_HOST}
      KONG_PG_PORT: 5432
      KONG_PG_USER: ${KONG_POSTGRES_USER}
      KONG_PG_PASSWORD: ${KONG_POSTGRES_PASSWORD}
      KONG_PG_DATABASE: ${KONG_POSTGRES_DB}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PLUGINS: "bundled,jwt"
    volumes:
      - ../kong/kong.yml:/tmp/kong.yml
      - ../kong/entrypoint.sh:/docker-entrypoint.sh
    entrypoint: ["/bin/sh", "/docker-entrypoint.sh"]

  user-service:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      secrets:
        - dotenv_user_key
    image: uit_go-user_service
    container_name: user-service
    ports:
      - "3001:3001"
    secrets:
      - dotenv_user_key
    depends_on:
      - user-db
      - rabbitmq
      - redis
      - kong
      - kong-database
    networks:
      - backend

  driver-service:
    build:
      context: .
      dockerfile: ./apps/driver/Dockerfile
      secrets:
        - dotenv_driver_key
    image: uit_go-driver_service
    container_name: driver-service
    secrets:
      - dotenv_driver_key
    ports:
      - "3003:3003"
    depends_on:
      - driver-db
      - rabbitmq
      - redis
      - kong
      - kong-database
    networks:
      - backend

  trip-service:
    build:
      context: .
      dockerfile: ./apps/trip/Dockerfile
      secrets:
        - dotenv_trip_key
    image: uit_go-trip_service
    container_name: trip-service
    secrets:
      - dotenv_trip_key
    ports:
      - "3002:3002"
    depends_on:
      - trip-db
      - rabbitmq
      - redis
      - kong
      - kong-database
    networks:
      - backend

  user-db:
    build:
      context: ./apps/user
      dockerfile: Dockerfile.db
    container_name: user-db
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - user-db-data:/var/lib/postgresql/data
    secrets:
      - dotenv_user_key

  driver-db:
    build:
      context: ./apps/driver
      dockerfile: Dockerfile.db
    container_name: driver-db
    ports:
      - "8005:8005"
    networks:
      - backend
    volumes:
      - driver-db-data:/home/dynamodblocal/data

  trip-db:
    build:
      context: ./apps/trip
      dockerfile: Dockerfile.db
      secrets:
        - dotenv_trip_key
    container_name: trip-db
    ports:
      - "3307:3306"
    networks:
      - backend
    secrets:
      - dotenv_trip_key
    volumes:
      - trip-db-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

secrets:
  dotenv_user_key:
    file: ./secrets/dotenv_user_key.txt
  dotenv_driver_key:
    file: ./secrets/dotenv_driver_key.txt
  dotenv_trip_key:
    file: ./secrets/dotenv_trip_key.txt

volumes:
  kong_pgdata:
  user-db-data:
  trip-db-data:
  driver-db-data:
