services:
  kong:
    build: 
      context: ../kong
    container_name: kong
    networks:
      - backend
    ports:
        - "8000:8000"   
        - "8443:8443"  
        - "8001:8001" 
        - "8444:8444"  
        - "9000:9000" 
        - "9443:9443"
    environment:
      KONG_DATABASE: "off"                         
      KONG_DECLARATIVE_CONFIG: /tmp/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: "bundled"           
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:9000 http2"
    volumes:
      - ../kong/kong.yml:/tmp/kong.yml               

  user-service:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      secrets:
        - dotenv_user_key
    image: uit_go-user_service
    container_name: user-service
    ports:
      - "3001:3001"
      - "50051:50051"
    secrets:
      - dotenv_user_key
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      kong:
        condition: service_started
      user-db:
        condition: service_started
    networks:
      - backend

  driver-service:
    build:
      context: .
      dockerfile: ./apps/driver/Dockerfile
      secrets:
        - dotenv_driver_key
    image: uit_go-driver_service
    container_name: driver-service
    secrets:
      - dotenv_driver_key
    ports:
      - "3003:3003"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      kong:
        condition: service_started
      user-db:
        condition: service_started
    networks:
      - backend

  trip-service:
    build:
      context: .
      dockerfile: ./apps/trip/Dockerfile
      secrets:
        - dotenv_trip_key
    image: uit_go-trip_service
    container_name: trip-service
    secrets:
      - dotenv_trip_key
    ports:
      - "3002:3002"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      kong:
        condition: service_started
      user-db:
        condition: service_started
    networks:
      - backend

  user-db:
    build:
      context: ./apps/user
      dockerfile: Dockerfile.db
    container_name: user-db
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - user-db-data:/var/lib/postgresql/data
    secrets:
      - dotenv_user_key

  driver-db:
    build:
      context: ./apps/driver
      dockerfile: Dockerfile.db
    container_name: driver-db
    ports:
      - "8005:8005"
    networks:
      - backend
    volumes:
      - driver-db-data:/home/dynamodblocal/data

  trip-db:
    build:
      context: ./apps/trip
      dockerfile: Dockerfile.db
      secrets:
        - dotenv_trip_key
    container_name: trip-db
    ports:
      - "3307:3306"
    networks:
      - backend
    secrets:
      - dotenv_trip_key
    volumes:
      - trip-db-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

secrets:
  dotenv_user_key:
    file: ./secrets/dotenv_user_key.txt
  dotenv_driver_key:
    file: ./secrets/dotenv_driver_key.txt
  dotenv_trip_key:
    file: ./secrets/dotenv_trip_key.txt

volumes:
  user-db-data:
  trip-db-data:
  driver-db-data:
