x-redis-deps: &redis-deps
    redis1:
      condition: service_started
    redis2:
      condition: service_started
    redis3:
      condition: service_started
    redis4:
      condition: service_started
    redis5:
      condition: service_started
    redis6:
      condition: service_started

services:
  kong:
    build: 
      context: ../kong
    container_name: kong
    image: uit-go_kong-api-gateway
    networks:
      - backend
    ports:
        - "8000:8000"   
        - "8443:8443"  
        - "8001:8001" 
        - "8444:8444"  
        - "9000:9000" 
        - "9443:9443"
    environment:
      KONG_DATABASE: "off"                         
      KONG_DECLARATIVE_CONFIG: /tmp/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: "bundled"           
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:9000 http2"
    volumes:
      - ../kong/kong.yml:/tmp/kong.yml               

  user-service:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      secrets:
        - dotenv_user_key
    image: uit_go-user_service
    container_name: user-service
    ports:
      - "3001:3001"
      - "50052:50051"
    secrets:
      - dotenv_user_key
    depends_on:
      rabbitmq:
        condition: service_healthy
      <<: *redis-deps
      kong:
        condition: service_started
      user-db:
        condition: service_started
    networks:
      - backend

  pulsar:
    image: apachepulsar/pulsar:3.3.2
    container_name: pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    command: >
      bin/pulsar standalone
    environment:
      PULSAR_MEM: "-Xms512m -Xmx512m"
    networks:
      - backend
    restart: unless-stopped

  driver-service:
    build:
      context: .
      dockerfile: ./apps/driver/Dockerfile
      secrets:
        - dotenv_driver_key
    image: uit_go-driver_service
    container_name: driver-service
    secrets:
      - dotenv_driver_key
    ports:
      - "3003:3003"
    depends_on:
      rabbitmq:
        condition: service_healthy
      <<: *redis-deps
      kong:
        condition: service_started
      driver-db:
        condition: service_started
    networks:
      - backend

  trip-service:
    build:
      context: .
      dockerfile: ./apps/trip/Dockerfile
      secrets:
        - dotenv_trip_key
    image: uit_go-trip_service
    container_name: trip-service
    secrets:
      - dotenv_trip_key
    ports:
      - "3002:3002"
    depends_on:
      rabbitmq:
        condition: service_healthy
      <<: *redis-deps
      kong:
        condition: service_started
      trip-db:
        condition: service_started
    networks:
      - backend

  notification-service:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      secrets:
          - dotenv_notification_key
    image: uit_go-notification_service
    container_name: notification-service
    secrets:
      - dotenv_notification_key
    ports:
      - "3004:3004"
    depends_on:
      rabbitmq:
        condition: service_healthy
      <<: *redis-deps
      kong:
        condition: service_started
      notification-db:
        condition: service_started
    networks:
      - backend

  user-db:
    build:
      context: ./apps/user
      dockerfile: Dockerfile.db
    container_name: user-db
    image: uit-go_user-db
    ports:
      - "5433:5432"
    networks:
      - backend
    volumes:
      - user-db-data:/var/lib/postgresql/data
    secrets:
      - dotenv_user_key

  driver-db:
    build:
      context: ./apps/driver
      dockerfile: Dockerfile.db
    container_name: driver-db
    image: uit-go_driver-db
    ports:
      - "8005:8005"
    networks:
      - backend
    volumes:
      - driver-db-data:/home/dynamodblocal/data

  trip-db:
    build:
      context: ./apps/trip
      dockerfile: Dockerfile.db
      secrets:
        - dotenv_trip_key
    container_name: trip-db
    image: uit-go_trip-db
    ports:
      - "3307:3306"
    networks:
      - backend
    secrets:
      - dotenv_trip_key
    volumes:
      - trip-db-data:/var/lib/mysql
    
  notification-db:
    build:
      context: ./apps/notification
      dockerfile: Dockerfile.db
    secrets:
      - dotenv_notification_key
      - mongo_root_password
    image: uit-go_notification-db
    container_name: notification-db
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
    volumes:
      - notification-db-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ../../infra/monitoring/k6:/scripts
      - ./proto:/proto
    networks:
      - backend
    environment:  
      K6_PROMETHEUS_RW_SERVER_URL: http://prometheus:9090/api/v1/write
    entrypoint: ["k6"]
    command:
      [
        "run",
        "--out",
        "experimental-prometheus-rw",
        "/scripts/loadtest.js"
      ]
    depends_on:
      - prometheus
      - user-service
      - trip-service
      - driver-service
      - notification-service

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - backend
    volumes:
      - ../../infra/monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  redis1:
    image: redis:6.2
    container_name: redis1
    ports:
      - "7000:7000"
      - "17000:17000"
    volumes:
      - redis-data1:/data
      - ./redis1.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend

  redis2:
    image: redis:6.2
    container_name: redis2
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - redis-data2:/data
      - ./redis2.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend

  redis3:
    image: redis:6.2
    container_name: redis3
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - redis-data3:/data
      - ./redis3.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend

  redis4:
    image: redis:6.2
    container_name: redis4
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - redis-data4:/data
      - ./redis4.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend

  redis5:
    image: redis:6.2
    container_name: redis5
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - redis-data5:/data
      - ./redis5.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend

  redis6:
    image: redis:6.2
    container_name: redis6
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - redis-data6:/data
      - ./redis6.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend

networks:
  backend:
    driver: bridge

secrets:
  dotenv_user_key:
    file: ./secrets/dotenv_user_key.txt
  dotenv_driver_key:
    file: ./secrets/dotenv_driver_key.txt
  dotenv_trip_key:
    file: ./secrets/dotenv_trip_key.txt
  dotenv_notification_key:
    file: ./secrets/dotenv_notification_key.txt
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt

volumes:
  user-db-data:
  trip-db-data:
  driver-db-data:
  notification-db-data:
  grafana-data:
  redis-data1:
  redis-data2:
  redis-data3:
  redis-data4:
  redis-data5:
  redis-data6:
