port 7003
bind 0.0.0.0
protected-mode no

dir /data
appendonly yes
appendfilename "appendonly.aof"

cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-require-full-coverage yes

loglevel notice
logfile ""

save 900 1
save 300 10
save 60 10000

tcp-keepalive 60
