port 7005
bind 0.0.0.0
protected-mode no

dir /data
appendonly yes
appendfilename "appendonly6.aof"

cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-require-full-coverage yes

cluster-announce-ip 192.168.28.94
cluster-announce-port 7005
cluster-announce-bus-port 17005

loglevel notice
logfile ""

tcp-keepalive 60
