port 7004
bind 0.0.0.0
protected-mode no

dir /data
appendonly yes
appendfilename "appendonly5.aof"

cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-require-full-coverage yes

# Redis Cluster announce (sử dụng IP VM 192.168.28.94)
cluster-announce-ip 192.168.28.94
cluster-announce-port 7004
cluster-announce-bus-port 17004

loglevel notice
logfile ""

save 900 1
save 300 10
save 60 10000

tcp-keepalive 60
