syntax = "proto3";

package driver;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "trip.proto";

service DriverService {
  rpc GetAllTripsOfDriver(GetAllTripsOfDriverRequest) 
    returns (GetAllTripsOfDriverResponse);
  rpc UpdateDriverStatusGrpc(UpdateDriverStatusGrpcRequest)
    returns (UpdateDriverStatusGrpcResponse);
  rpc UpdateDriverApproval(UpdateDriverApprovalRequest)
    returns (UpdateDriverApprovalResponse);
  rpc GetDriverApprovals(GetDriverApprovalsRequest)
    returns (GetDriverApprovalsResponse);
  rpc GetLocationOfDriver(GetLocationOfDriverRequest)
    returns (DriverLocation); 
  rpc GetDriverInfoDetailById(GetDriverInfoDetailByIdRequest)
    returns (GetDriverInfoDetailByIdResponse);
  rpc FindAvailableDrivers(FindAvailableDriversRequest)
    returns (FindAvailableDriversResponse);
  rpc UpdateDriverLocation(UpdateDriverLocationRequest)
    returns (UpdateDriverLocationResponse);
  rpc GetDrivers(GetDriversRequest) returns (GetDriversResponse);
}

message GetDriverInfoDetailByIdResponse {
  string id = 1;
  string email = 2;
  string role = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
  optional DriverInfo driver_info = 6;
  UserProfile profile = 7;
}

message User {
  string id = 1;
  string email = 2;
  string password = 3;
  string role = 4;
  google.protobuf.Timestamp created_at = 5;
  google.protobuf.Timestamp updated_at = 6;
}

message UserProfile {
  string id = 1;
  string full_name = 2;
  string phone_number = 3;
  string address = 4;
  google.protobuf.Timestamp birth_day = 5;
  optional User user = 6;
}

message GetDriversRequest {
  optional string status = 1;
}

message GetDriversResponse {
  repeated GetDriversData drivers = 1;
}

message GetDriversData {
  string user_id = 1;
  string driver_id = 2;
  int32 total_trip = 3;
  double rating = 4;
  google.protobuf.Timestamp license_expiry = 5;
  string license_number = 6;
  string status = 7;
  optional string current_trip_id = 8;
  optional VehicleCached vehicle_cached = 9;
  google.protobuf.Timestamp last_seen_at = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 12;
  optional Location location = 13;
}

message Location {
  double lat = 1;
  double lng = 2;
}

message UpdateDriverLocationRequest {
  string current_location = 1;
}

message UpdateDriverLocationResponse {
  string message = 1;
  bool success = 2;
  GeoData data = 3;
}

message GeoData {
  double lat = 1;
  double lng = 3;
}

message NearbyDriver {
  string driver_id = 1;
  double lat = 2;
  double lng = 3;
  double distance_km = 4;
  optional VehicleCached vehicle = 5;
}

message FindAvailableDriversRequest {
  double lat = 1;
  double lng = 2;
}

message FindAvailableDriversResponse {
  int32 count = 1;
  repeated NearbyDriver drivers = 2;
}

message GetDriverInfoDetailByIdRequest {
  string driver_id = 1;
}

message GetLocationOfDriverRequest {
  string driver_id = 1;
}

message GetLocationOfDriverRespose {

}

message GetDriverApprovalsRequest {
  optional string status = 1;
}

message GetDriverApprovalsResponse {
  repeated GetDriverApprovalsFormatted approvals = 1;
}

message GetDriverApprovalsFormatted {
  string driver_approval_id = 1;
  string status = 2;
  google.protobuf.Timestamp reviewed_date = 3;
  optional string note = 4;
  string driver_id = 5;
  string vehicle_id = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}

message UpdateDriverApprovalRequest {
  string status = 1;
  optional string note = 2;
  string driver_approval_id = 3;
}

message UpdateDriverApprovalData {
  string driver_approval_id = 1;
  string status = 2;
  google.protobuf.Timestamp reviewed_date = 3;
  optional string note = 4;
  string driver_id = 5;
  string vehicle_id = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}

message UpdateDriverApprovalResponse {
  string message = 1;
  UpdateDriverApprovalData data = 2;
}

message UpdateDriverStatusGrpcRequest {
  string status = 1;
  string driver_id = 2;
  optional string current_location = 3;
  optional string current_trip_id = 4;
}

message UpdateDriverStatusGrpcResponse {
  string message = 1;
  google.protobuf.Struct data = 2;
}

message GetAllTripsOfDriverRequest {
  optional string after_cursor = 1;
}

message GetAllTripsOfDriverResponse {
  optional string after_cursor = 1;
  repeated trip.Trip data = 2;
}

message Driver {
  string driver_id = 1;
  string user_id = 2;
  double rating = 3;
  int32 total_trip = 4;
  string license_number = 5;
  google.protobuf.Timestamp license_expiry = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}

message DriverApproval {
  string driver_approval_id = 1;
  string status = 2;
  google.protobuf.Timestamp reviewed_date = 3;
  optional string note = 4;
  string driver_id = 5;
  string vehicle_id = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}

message DriverLocation {
  string hash_prefix = 1;
  string driver_id = 2;
  string geo_hash = 3;
  double lat = 4;
  double lng = 5;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}

message VehicleCached {
  string vehicle_id = 1;
  string plate_number = 2;
  string brand = 3;
  string model = 4;
  string color = 5;
}

message DriverStatusModel {
  string driver_id = 1;
  string status = 2;
  google.protobuf.Timestamp last_seen_at = 3;
  string current_trip_id = 4;
  VehicleCached vehicle_cached = 5;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}

message Vehicle {
  string vehicle_id = 1;
  string driver_id = 2;
  string plate_number = 3;
  string brand = 4;
  string model = 5;
  string color = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}

message DriverInfo {
  string driver_id = 1;
  string user_id = 2;
  double rating = 3;
  int32 total_trip = 4;
  string license_number = 5;
  google.protobuf.Timestamp license_expiry = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
  DriverStatusModel driver_status = 9;
  DriverApproval driver_approval = 10;
  DriverLocation driver_location = 11;
  Vehicle vehicle = 12;
}