syntax = "proto3";

package notification;

import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

service NotificationService {
  rpc GetNotificationsOfUser(GetNotificationsOfUserRequest) 
    returns (GetNotificationsOfUserResponse);
}

message Notification {
  string id = 1;
  string title = 2;
  string type = 3;
}

message UserNotification {
  Notification notification = 1;
  google.protobuf.Timestamp created_at = 2;
  string message = 5;
  bool read = 3;
  google.protobuf.Timestamp read_at = 4;
  optional google.protobuf.Struct data = 6;
}

message GetNotificationsOfUserRequest {
  optional bool read = 1;
}

message GetNotificationsOfUserResponse {
  repeated UserNotification notifications = 1;
}