syntax = "proto3";

package trip;

import "google/protobuf/timestamp.proto";

service TripService {
  rpc GetTrip(GetTripRequest) returns (GetTripResponse); 
  rpc CreateTrip(CreateTripRequest) returns (CreateTripResponse);
  rpc UpdateTrip(UpdateTripRequest) returns (UpdateTripResponse);
  rpc UpdateTripRequestStatus(UpdateTripRequestStatusRequest) 
    returns (UpdateTripRequestStatusResponse);
  rpc GetEstimate(GetEstimateRequest) returns (GetEstimateResponse);
  rpc RateTrip(RateTripRequest) returns (RateTripResponse);
  rpc CancelTrip(CancelTripRequest) returns (CancelTripResponse);
}

message Trip {
  string id = 1;
  string origin_address = 2;
  string destination_address = 3;
  float origin_lat = 4;
  float destination_lat = 5;
  float origin_lng = 6;
  float destination_lng = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
  optional string note = 10;
  string passenger_id = 11;
  string driver_id = 12;
  float fare_final = 13;
  float fare_estimate = 14;
  string status = 15;
}

message CancelTripRequest {
  string trip_id = 1;
}

message CancelTripResponse {

}

message RateTripRequest {
  int32 rating = 1;
  string comment = 2;
}

message RateTripResponseData {
  string trip_id = 1;
  string driver_id = 2;
  int32 rating = 3;
  optional string comment = 4;
}

message RateTripResponse {
  string message = 1;
  bool success = 2;
  RateTripResponseData data = 3;
}

message GetEstimateRequest {
  string origin_address = 1;
  string destination_address = 2;
}

message GetEstimateResponse {
  string estimate_fare = 1;
}

message UpdateTripRequestStatusRequest {
  string status = 1;
  string trip_request_id = 2;
}

message UpdateTripRequestStatusResponse {
  string message = 1;
}

message UpdateTripRequest {
  optional string status = 1;
  optional string note = 2;
  optional string destination_address = 3;
  optional float fare_final = 4;
  string trip_id = 5;
}

message UpdateTripResponse {

}

message CreateTripRequest {
  string origin_address = 1;
  string destination_address = 2;
  optional string note = 3;
}

message Customer {
  string id = 1;
}

message Origin {
  string address = 1;
  float lat = 2;
  float lon = 3;
}

message Destination {
  string address = 1;
  float lat = 2;
  float lon = 3;
}

message Data {
  string id = 1;
  string status = 2;
  float distance_km = 3;
  Destination destination = 4;
  Origin origin = 5;
  string estimated_price = 6;
  google.protobuf.Timestamp created_at = 7;
  Customer customer = 8;
}

message CreateTripResponse {
  string message = 1;
}

message GetTripRequest {
  string trip_id = 1;
}

message GetTripResponse {
  string id = 1;
  string origin_address = 2;
  string destination_address = 3;
  float origin_lat = 4;
  float destination_lat = 5;
  float origin_lng = 6;
  float destination_lng = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
  optional string note = 10;
  string passenger_id = 11;
  string driver_id = 12;
  float fare_final = 13;
  float fare_estimate = 14;
  string status = 15;
}