# syntax=docker/dockerfile:1.5
FROM postgres:15

WORKDIR /apps/user

RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && npm install -g @dotenvx/dotenvx

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
COPY .env /apps/user/.env

RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 5432
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
