FROM mongo:6.0

EXPOSE 27017

ENV MONGO_INITDB_ROOT_USERNAME=notification
ENV MONGO_INITDB_DATABASE=notification_db

COPY ./entrypoint.sh /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/entrypoint.sh
