# syntax=docker/dockerfile:1.5
FROM amazon/dynamodb-local:latest

WORKDIR /home/dynamodblocal

RUN mkdir -p /home/dynamodblocal/data

EXPOSE 8005

CMD ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data", "-port", "8005"]
