// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: driver.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { wrappers } from 'protobufjs';
import { Observable } from 'rxjs';

export const protobufPackage = 'driver';

export enum DriverApprovalStatus {
  DRIVER_APPROVAL_STATUS_UNSPECIFIED = 0,
  DRIVER_APPROVAL_STATUS_PENDING = 1,
  DRIVER_APPROVAL_STATUS_ACCEPTED = 2,
  DRIVER_APPROVAL_STATUS_REJECTED = 3,
  UNRECOGNIZED = -1,
}

export enum DriverStatus {
  DRIVER_STATUS_UNSPECIFIED = 0,
  DRIVER_STATUS_ONLINE = 1,
  DRIVER_STATUS_OFFLINE = 2,
  DRIVER_STATUS_BUSY = 3,
  UNRECOGNIZED = -1,
}

export interface GetDriverApprovalsRequest {
  status?: DriverApprovalStatus | undefined;
}

export interface GetDriverApprovalsResponse {}

export interface UpdateDriverApprovalRequest {
  status: DriverApprovalStatus;
  note: string | undefined;
}

export interface UpdateDriverApprovalResponse {}

export interface UpdateDriverStatusGrpcRequest {
  status: DriverStatus;
}

export interface UpdateDriverStatusGrpcResponse {}

export interface GetAllTripsOfDriverRequest {
  afterCursor: string | undefined;
}

export interface GetAllTripsOfDriverResponse {}

export interface Driver {
  driverId: string;
  userId: string;
  rating: number;
  totalTrip: number;
  licenseNumber: string;
  licenseExpiry: Date | undefined;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface DriverApproval {
  driverApprovalId: string;
  status: DriverApprovalStatus;
  reviewedDate?: Date | undefined;
  note: string | undefined;
  driverId: string;
  vehicleId: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface DriverLocation {
  hashPrefix: string;
  driverId: string;
  geoHash: string;
  lat: number;
  lng: number;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface VehicleCached {
  vehicleId: string;
  plateNumber: string;
  brand: string;
  model: string;
}

export interface DriverStatusModel {
  driverId: string;
  status: DriverStatus;
  lastSeenAt: Date | undefined;
  currentTripId: string;
  vehicleCached: VehicleCached | undefined;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface Vehicle {
  vehicleId: string;
  driverId: string;
  plateNumber: string;
  brand: string;
  model: string;
  color: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface DriverInfo {
  driverId: string;
  userId: string;
  rating: number;
  totalTrip: number;
  licenseNumber: string;
  licenseExpiry: Date | undefined;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
  driverStatus: DriverStatus;
  driverApproval: DriverApproval | undefined;
  driverLocation: DriverLocation | undefined;
  vehicle: Vehicle | undefined;
}

export const DRIVER_PACKAGE_NAME = 'driver';

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return {
      seconds: value.getTime() / 1000,
      nanos: (value.getTime() % 1000) * 1e6,
    };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface DriverServiceClient {
  getAllTripsOfDriver(
    request: GetAllTripsOfDriverRequest,
  ): Observable<GetAllTripsOfDriverResponse>;

  updateDriverStatusGrpc(
    request: UpdateDriverStatusGrpcRequest,
  ): Observable<UpdateDriverStatusGrpcResponse>;

  updateDriverApproval(
    request: UpdateDriverApprovalRequest,
  ): Observable<UpdateDriverApprovalResponse>;

  getDriverApprovals(
    request: GetDriverApprovalsRequest,
  ): Observable<GetDriverApprovalsResponse>;
}

export interface DriverServiceController {
  getAllTripsOfDriver(
    request: GetAllTripsOfDriverRequest,
  ):
    | Promise<GetAllTripsOfDriverResponse>
    | Observable<GetAllTripsOfDriverResponse>
    | GetAllTripsOfDriverResponse;

  updateDriverStatusGrpc(
    request: UpdateDriverStatusGrpcRequest,
  ):
    | Promise<UpdateDriverStatusGrpcResponse>
    | Observable<UpdateDriverStatusGrpcResponse>
    | UpdateDriverStatusGrpcResponse;

  updateDriverApproval(
    request: UpdateDriverApprovalRequest,
  ):
    | Promise<UpdateDriverApprovalResponse>
    | Observable<UpdateDriverApprovalResponse>
    | UpdateDriverApprovalResponse;

  getDriverApprovals(
    request: GetDriverApprovalsRequest,
  ):
    | Promise<GetDriverApprovalsResponse>
    | Observable<GetDriverApprovalsResponse>
    | GetDriverApprovalsResponse;
}

export function DriverServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'getAllTripsOfDriver',
      'updateDriverStatusGrpc',
      'updateDriverApproval',
      'getDriverApprovals',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('DriverService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('DriverService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const DRIVER_SERVICE_NAME = 'DriverService';
