// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: notification.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { wrappers } from 'protobufjs';
import { Observable } from 'rxjs';
import { Struct } from './google/protobuf/struct';

export const protobufPackage = 'notification';

export interface Notification {
  id: string;
  title: string;
  type: string;
}

export interface UserNotification {
  notification: Notification | undefined;
  createdAt: Date | undefined;
  message: string;
  read: boolean;
  readAt: Date | undefined;
  data?: { [key: string]: any } | undefined;
}

export interface GetNotificationsOfUserRequest {
  read?: boolean | undefined;
}

export interface GetNotificationsOfUserResponse {
  notifications: UserNotification[];
}

export const NOTIFICATION_PACKAGE_NAME = 'notification';

wrappers['.google.protobuf.Timestamp'] = {
  fromObject(value: Date) {
    return {
      seconds: value.getTime() / 1000,
      nanos: (value.getTime() % 1000) * 1e6,
    };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

wrappers['.google.protobuf.Struct'] = {
  fromObject: Struct.wrap,
  toObject: Struct.unwrap,
} as any;

export interface NotificationServiceClient {
  getNotificationsOfUser(
    request: GetNotificationsOfUserRequest,
  ): Observable<GetNotificationsOfUserResponse>;
}

export interface NotificationServiceController {
  getNotificationsOfUser(
    request: GetNotificationsOfUserRequest,
  ):
    | Promise<GetNotificationsOfUserResponse>
    | Observable<GetNotificationsOfUserResponse>
    | GetNotificationsOfUserResponse;
}

export function NotificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['getNotificationsOfUser'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('NotificationService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('NotificationService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = 'NotificationService';
