// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: trip.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";

export const protobufPackage = "trip";

export enum TripStatus {
  TRIP_STATUS_UNSPECIFIED = 0,
  TRIP_STATUS_SEARCHING = 1,
  TRIP_STATUS_ACCEPTED = 2,
  TRIP_STATUS_ONGOING = 3,
  TRIP_STATUS_COMPLETED = 4,
  TRIP_STATUS_CANCELLED = 5,
  TRIP_STATUS_ARRIVING = 6,
  TRIP_STATUS_STARTED = 7,
  UNRECOGNIZED = -1,
}

export enum TripRequestStatus {
  TRIP_REQUEST_STATUS_UNSPECIFIED = 0,
  TRIP_REQUEST_STATUS_ACCEPTED = 1,
  TRIP_REQUEST_STATUS_REJECTED = 2,
  TRIP_REQUEST_STATUS_TIMEOUT = 3,
  TRIP_REQUEST_STATUS_PENDING = 4,
  UNRECOGNIZED = -1,
}

export interface Trip {
  id: string;
  originAddress: string;
  destinationAddress: string;
  originLat: number;
  destinationLat: number;
  originLng: number;
  destinationLng: number;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
  note?: string | undefined;
  passengerId: string;
  driverId: string;
  fareFinal: number;
  fareEstimate: number;
  status: TripStatus;
}

export interface CancelTripRequest {
  tripId: string;
}

export interface CancelTripResponse {
}

export interface RateTripRequest {
  rating: number;
  comment: string;
}

export interface RateTripResponseData {
  tripId: string;
  driverId: string;
  rating: number;
  comment?: string | undefined;
}

export interface RateTripResponse {
  message: string;
  success: boolean;
  data: RateTripResponseData | undefined;
}

export interface GetEstimateRequest {
  originAddress: string;
  destinationAddress: string;
}

export interface GetEstimateResponse {
  estimateFare: string;
}

export interface UpdateTripRequestStatusRequest {
  status: TripRequestStatus;
  tripId: string;
}

export interface UpdateTripRequestStatusResponse {
}

export interface UpdateTripRequest {
  status?: TripStatus | undefined;
  note: string | undefined;
  destinationAddress: string | undefined;
  fareFinal?: number | undefined;
  tripId: string;
}

export interface UpdateTripResponse {
}

export interface CreateTripRequest {
  originAddress: string;
  destinationAddress: string;
  note: string | undefined;
}

export interface Customer {
  id: string;
}

export interface Origin {
  address: string;
  lat: number;
  lon: number;
}

export interface Destination {
  address: string;
  lat: number;
  lon: number;
}

export interface Data {
  id: string;
  status: string;
  distanceKm: number;
  destination: Destination | undefined;
  origin: Origin | undefined;
  estimatedPrice: string;
  createdAt: Date | undefined;
  customer: Customer | undefined;
}

export interface CreateTripResponse {
  message: string;
}

export interface GetTripRequest {
  tripId: string;
}

export interface GetTripResponse {
  id: string;
  originAddress: string;
  destinationAddress: string;
  originLat: number;
  destinationLat: number;
  originLng: number;
  destinationLng: number;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
  note?: string | undefined;
  passengerId: string;
  driverId: string;
  fareFinal: number;
  fareEstimate: number;
  status: string;
}

export const TRIP_PACKAGE_NAME = "trip";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface TripServiceClient {
  getTrip(request: GetTripRequest): Observable<GetTripResponse>;

  createTrip(request: CreateTripRequest): Observable<CreateTripResponse>;

  updateTrip(request: UpdateTripRequest): Observable<UpdateTripResponse>;

  updateTripRequestStatus(request: UpdateTripRequestStatusRequest): Observable<UpdateTripRequestStatusResponse>;

  getEstimate(request: GetEstimateRequest): Observable<GetEstimateResponse>;

  rateTrip(request: RateTripRequest): Observable<RateTripResponse>;

  cancelTrip(request: CancelTripRequest): Observable<CancelTripResponse>;
}

export interface TripServiceController {
  getTrip(request: GetTripRequest): Promise<GetTripResponse> | Observable<GetTripResponse> | GetTripResponse;

  createTrip(
    request: CreateTripRequest,
  ): Promise<CreateTripResponse> | Observable<CreateTripResponse> | CreateTripResponse;

  updateTrip(
    request: UpdateTripRequest,
  ): Promise<UpdateTripResponse> | Observable<UpdateTripResponse> | UpdateTripResponse;

  updateTripRequestStatus(
    request: UpdateTripRequestStatusRequest,
  ):
    | Promise<UpdateTripRequestStatusResponse>
    | Observable<UpdateTripRequestStatusResponse>
    | UpdateTripRequestStatusResponse;

  getEstimate(
    request: GetEstimateRequest,
  ): Promise<GetEstimateResponse> | Observable<GetEstimateResponse> | GetEstimateResponse;

  rateTrip(request: RateTripRequest): Promise<RateTripResponse> | Observable<RateTripResponse> | RateTripResponse;

  cancelTrip(
    request: CancelTripRequest,
  ): Promise<CancelTripResponse> | Observable<CancelTripResponse> | CancelTripResponse;
}

export function TripServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getTrip",
      "createTrip",
      "updateTrip",
      "updateTripRequestStatus",
      "getEstimate",
      "rateTrip",
      "cancelTrip",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TripService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TripService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TRIP_SERVICE_NAME = "TripService";
