// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.0
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { wrappers } from "protobufjs";
import { Observable } from "rxjs";
import { DriverInfo } from "./driver";

export const protobufPackage = "user";

export enum UserRole {
  USER_ROLE_UNSPECIFIED = 0,
  USER_ROLE_CUSTOMER = 1,
  USER_ROLE_DRIVER = 2,
  USER_ROLE_ADMIN = 3,
  UNRECOGNIZED = -1,
}

export interface User {
  id: string;
  email: string;
  password: string;
  role: UserRole;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface UserProfile {
  id: string;
  fullName: string;
  phoneNumber: string;
  address: string;
  birthDay: Date | undefined;
  user?: User | undefined;
}

export interface GetMeRequest {
}

export interface GetMeResponse {
  id: string;
  email: string;
  role: string;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
  driverInfo?: DriverInfo | undefined;
  profile: UserProfile | undefined;
}

export interface UpdateProfileRequest {
  fullName?: string | undefined;
  phoneNumber?: string | undefined;
  address?: string | undefined;
  birthDay: Date | undefined;
}

export interface UpdateProfileResponse {
  id: string;
  fullName: string;
  phoneNumber: string;
  address: string;
  birthDay: Date | undefined;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface CreateDriverRequest {
  licenseNumber: string;
  licenseExpiry: Date | undefined;
  plateNumber: string;
  brand: string;
  model: string;
  color: string;
}

export interface RegisterRequest {
  email: string;
  password: string;
  role: UserRole;
  fullName: string;
  phoneNumber: string;
  phoneAddress: string;
  birthDay: Date | undefined;
  createDriverRequest: CreateDriverRequest | undefined;
  address: string;
}

export interface UserData {
  sub: string;
  fullName: string;
  email: string;
  role: string;
}

export interface RegisterResponse {
  message: string;
  success: boolean;
  data: UserData | undefined;
}

export interface LoginResponse {
  accessToken: string;
}

export const USER_PACKAGE_NAME = "user";

wrappers[".google.protobuf.Timestamp"] = {
  fromObject(value: Date) {
    return { seconds: value.getTime() / 1000, nanos: (value.getTime() % 1000) * 1e6 };
  },
  toObject(message: { seconds: number; nanos: number }) {
    return new Date(message.seconds * 1000 + message.nanos / 1e6);
  },
} as any;

export interface UserServiceClient {
  login(request: LoginRequest): Observable<LoginResponse>;

  updateProfile(request: UpdateProfileRequest): Observable<GetMeResponse>;

  register(request: RegisterRequest): Observable<RegisterResponse>;

  getMe(request: GetMeRequest): Observable<GetMeResponse>;
}

export interface UserServiceController {
  login(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  updateProfile(request: UpdateProfileRequest): Promise<GetMeResponse> | Observable<GetMeResponse> | GetMeResponse;

  register(request: RegisterRequest): Promise<RegisterResponse> | Observable<RegisterResponse> | RegisterResponse;

  getMe(request: GetMeRequest): Promise<GetMeResponse> | Observable<GetMeResponse> | GetMeResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["login", "updateProfile", "register", "getMe"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
